export default {

	MAIN_VERTICAL_PADDING: 2,
	MAIN_HORIZONTAL_PADDING: 3,

	SIDENAV_FULL_WIDTH: 18,
	SIDENAV_CLOSE_WIDTH: 6,
	SIDENAV_ICON_SIZE: 2,

	COLOR_LIGHT: 'rgba(255, 255, 255, 0.9)',
	COLOR_PRIMARY: '#8E24AA',
};