const Theme = {

	DEFAULT_VERTICAL_PADDING: 2,
	DEFAULT_HORIZONTAL_PADDING: 3,
	
	SIDENAV_FULL_WIDTH: 18,
	SIDENAV_CLOSE_WIDTH: 6,
	SIDENAV_ICON_SIZE: 2,
	
	COLOR_LIGHT: '#FFFFFF',
	COLOR_DARK: '#263238',
	COLOR_PRIMARY: '#8E24AA',
	
	SHADOW_BLUR: 4,
	SHADOW_BLUR_MEDIUM: 8,
	SHADOW_BLUR_LARGE: 14,
	SHADOW_OFFSET: 2,
	SHADOW_COLOR: 'rgba(0, 0, 0, 0.1)',

};

export default Theme;