const Theme = {

	ANIMATION_SPEED: 0.3,

	DEFAULT_VERTICAL_PADDING: 2,
	DEFAULT_HORIZONTAL_PADDING: 3,
	
	SIDENAV_FULL_WIDTH: 14,
	SIDENAV_CLOSE_WIDTH: 6,
	SIDENAV_ICON_SIZE: 2,
	SIDENAV_FONT_SIZE: 1.2,
	
	COLOR_LIGHT: '#FFFFFF',
	COLOR_DARK: '#263238',
	COLOR_PRIMARY: '#F4511E',
	
	SHADOW_BLUR: 4,
	SHADOW_BLUR_MEDIUM: 8,
	SHADOW_BLUR_LARGE: 14,
	SHADOW_OFFSET: 2,
	SHADOW_COLOR: 'rgba(0, 0, 0, 0.08)',

};

export default Theme;