
export default {

	ANIMATION_SPEED: 0.3, // seconds

	DEFAULT_REM_SIZE: 16, //px

	FONT_PRIMARY: 'Manjari',
	FONT_CONDENSED: 'Barlow Condensed',
	FONT_DEFAULT_SIZE: 1, // rem
	FONT_DEFAULT_WEIGHT: 400,
	FONT_MEDIUM_WEIGHT: 500,
	FONT_STRONG_WEIGHT: 700,
	
	ROUNDED_BORDER: 4, // px

	TITLE_SPACING_TOP: 2, // rem
	TITLE_SPACING_BOTTOM: 1, // rem

	DEFAULT_VERTICAL_PADDING: 2, // rem
	DEFAULT_HORIZONTAL_PADDING: 3, // rem
	
	SIDENAV_FULL_WIDTH: 12, // rem
	SIDENAV_CLOSE_WIDTH: 4, // rem
	SIDENAV_ICON_SIZE: 1.2, // rem
	SIDENAV_FONT_SIZE: 1, // rem

	SIDECONTENT_WIDTH: 50, // vw
	
	COLOR_BASE: '#FFFFFF',
	COLOR_BASE_2: '#F8FAFB',
	COLOR_PRIMARY: '#263238',
	COLOR_BRAND: '#F4511E',
	
	SHADOWS_ENABLED: true,
	SHADOW_BLUR: 8, // rem
	SHADOW_OFFSET: 2, // rem
	SHADOW_COLOR: 'rgba(0, 0, 0, 0.1)',

	GRID_DEFAULT_GAP: 1, // rem

	CARD_IMAGE_HEIGHT: 10, // rem
	CARD_RADIUS: 10, // px
	CARD_PADDING: 1, // rem
	CARD_DESCRIPTION_SIZE: 0.8, // rem
	CARD_DESCRIPTION_LIMIT: 75, // chars,
	CARD_SELECTED_BORDER_SIZE: 2, // px
	CARD_SELECTED_EXPAND: 1.05, // 1 is normal scale
	
	FORM_SCALE: 0.2,
	INPUT_TOP_BOTTOM_PADDING: 0.5,
	INPUT_SIDE_PADDING: 0.5

};